<a href="https://colab.research.google.com/github/vic1030/Data_Science_Learning/blob/main/05_Numpy%E7%9A%84%E6%95%B0%E5%AD%A6%E7%BB%9F%E8%AE%A1%E5%87%BD%E6%95%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy的数学统计函数

本节内容：

#### 1、Numpy有哪些数学统计函数：  
<table style="margin-left:0px; text-align:left;">
    <tr><th>函数名</th><th>说明</th></tr>
    <tr><td>np.sum</td><td>所有元素的和</td></tr>
    <tr><td>np.prod</td><td>所有元素的乘积</td></tr>
    <tr><td>np.cumsum</td><td>元素的累积加和</td></tr>
    <tr><td>np.cumprod</td><td>元素的累积乘积</td></tr>
    <tr><td>np.min</td><td>最小值</td></tr>
    <tr><td>np.max</td><td>最大值</td></tr>
    <tr><td>np.percentile</td><td>0-100百分位数</td></tr>
    <tr><td>np.quantile</td><td>0-1分位数</td></tr>
    <tr><td>np.median</td><td>中位数</td></tr>
    <tr><td>np.average</td><td>加权平均，参数可以指定weights</td></tr>
    <tr><td>np.mean</td><td>平均值</td></tr>
    <tr><td>np.std</td><td>标准差</td></tr>
    <tr><td>np.var</td><td>方差</td></tr>
</table>

#### 2、怎样实现按不同的axis计算
以上函数，都有一个参数叫做axis用于指定计算轴为行还是列，如果不指定，那么会计算所有元素的结果

#### 3、实例：机器学习将数据进行标准化
A = (A - mean(A, axis=0)) / std(A, axis=0)

### 1、Numpy的数学统计函数

In [1]:
import numpy as np

In [14]:
arr = np.arange(0,12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
np.sum(arr)

66

In [16]:
np.prod(arr)

0

In [17]:
np.cumsum(arr)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [18]:
np.cumprod(arr)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.min(arr)

0

In [20]:
np.max(arr)

11

In [22]:
np.percentile(arr, [25, 50, 75]) #percentile:https://blog.csdn.net/kuaileky/article/details/105544050 1，（12+1)*(25/100)= 3.25 2. 去寻找排列后的对应两位数(此例:2&3) 3.2+0.25*(3-2)

array([2.75, 5.5 , 8.25])

In [24]:
np.quantile(arr, [0.25, 0.5, 0.75])

array([2.75, 5.5 , 8.25])

In [25]:
np.median(arr)

5.5

In [26]:
np.mean(arr)

5.5

In [27]:
np.std(arr)

3.452052529534663

In [28]:
np.var(arr)

11.916666666666666

In [29]:
# weights的shape需要和arr一样
weights = np.random.rand(*arr.shape)
np.average(arr, weights=weights)

5.6994660778131605

### 2、Numpy的axis参数的用途

axis=0代表行、axis=1代表列

对于sum/mean/media等聚合函数：
* 理解1：axis=0代表把行消解掉，axis=1代表把列消解掉
* 理解2：axis=0代表跨行计算，axis=1代表跨列计算

In [30]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
arr.sum(axis=0) #axis=0代表把行消解掉

array([12, 15, 18, 21])

In [32]:
arr.sum(axis=1) #axis=1代表把列消解掉

array([ 6, 22, 38])

In [33]:
arr.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [34]:
arr.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

### 3、实例：机器学习将数据进行标准化

In [35]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

arr如果对应到现实世界的一种解释：
* 行：每行对应一个样本数据
* 列：每列代表样本的一个特征

数据标准化：  
* 对于机器学习、神经网络来说，不同列的量纲应该相同，训练收敛的更快；
* 比如商品的价格是0到100元、销量是1万到10万个，这俩数字没有可比性，因此需要先都做标准化；
* 不同列代表不同的特征，因此需要axis=0做计算
* 标准化一般使用A = (A - mean(A, axis=0)) / std(A, axis=0)公式进行

In [36]:
# 计算每列的均值
mean = np.mean(arr, axis=0)
mean

array([4., 5., 6., 7.])

In [37]:
# 计算每列的方差
std = np.std(arr, axis=0)
std

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [ ]:
# 计算分子，注意每行都会分别减去[4., 5., 6., 7.]，这叫做numpy的广播
fenzi = arr-mean
fenzi

array([[-4., -4., -4., -4.],
       [ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.]])

In [ ]:
result = fenzi/std
result

array([[-1.22474487, -1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487,  1.22474487]])

#### 用随机数再试一次

In [38]:
arr2 = np.random.randint(1, 100, size=(3,4))
arr2

array([[96, 45,  6, 99],
       [ 4, 42, 45, 96],
       [41, 54, 45, 24]])

In [39]:
result = (arr2 - np.mean(arr2,axis=0)) / np.std(arr2,axis=0)
result

array([[ 1.29637493, -0.39223227, -1.41421356,  0.74993067],
       [-1.13763514, -0.98058068,  0.70710678,  0.66340021],
       [-0.15873979,  1.37281295,  0.70710678, -1.41333087]])